on:
  repository_dispatch:
    events:
      - create_feature

jobs:
  create_feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.ref }}

      - name: Run Agent Command to create feature
        uses: a5c-ai/runner@main
        id: feature
        env:
          feature_slug_name: ${{ github.event.client_payload.feature_slug_name }}
          event_id: ${{ github.event.client_payload.event_id }}
        with:
          # extracts the event
          github_token: ${{ secrets.GITHUB_TOKEN }}
          inputs:
            feature_slug_name: ${{ env.feature_slug_name }}
            event_id: ${{ env.event_id }}
          prompt_uri: "https://raw.githubusercontent.com/a5c-ai/a5c-githubaction/main/commands/feature.md"
