name: Reactor
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issue_comment:
    types: [created, edited, deleted]
  issues:
    types: [opened, edited, deleted]
  repository_dispatch:
    events: [reactor]


jobs:
  reactor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Reactor
        uses: a5c-ai/reactor@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_event: ${{ github.event }}
      - name: Emit event
        run: |
          echo "Emitting event"
          # emit a repository_dispatch event
          echo "Emitting repository_dispatch event"
          # prepare the json data file, include the original event data
          cat <<EOF > json_data.json
          {
            "event_type": "create-feature",
            "client_payload": ${{ toJson(github.event) }}
          }
          EOF
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d "@json_data.json" "https://api.github.com/repos/${{ github.repository }}/dispatches"
          echo "Reacting..."