trigger: none

pr: none

stages:
  - stage: Reactor
    displayName: Reactor Jobs
    jobs:
      - template: .azure/templates/a5c-base.yml
        parameters:
          jobName: Reactor_Main
          displayName: Reactor (main branches)
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
      - template: .azure/templates/a5c-base.yml
        parameters:
          jobName: Reactor_Feature
          displayName: Reactor (feature branches)
          condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
      - template: .azure/templates/a5c-base.yml
        parameters:
          jobName: Reactor_PR
          displayName: Reactor (pull requests)
          condition: eq(variables['Build.Reason'], 'PullRequest')