version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Optional time window; keeps runs predictable
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "ci"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      types:
        patterns:
          - "@types/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
