remote_agents:
  enabled: true
  cache_timeout: 120
  retry_attempts: 5
  retry_delay: 2000
  sources:
    individual:
      - uri: https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/project-seeder-agent.agent.md
        alias: project-seeder-agent
a5c_auto_mode: true
