triggers:
  validation:
    enabled: true
  triage:
    enabled: true
  create_pr:
    enabled: true

remote_agents:
  enabled: true
  cache_timeout: 120
  retry_attempts: 5
  retry_delay: 2000
  sources:
    individual:
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/developer-agent.agent.md"
        alias: "developer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/validator-agent.agent.md"
        alias: "validator-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/build-fixer-agent.agent.md"
        alias: "build-fixer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/research/researcher-base-agent.agent.md"
        alias: "researcher-base-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/communication/content-writer-agent.agent.md"
        alias: "content-writer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/producer-agent.agent.md"
        alias: "producer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/conflict-resolver-agent.agent.md"
        alias: "conflict-resolver-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/recruiter-agent.agent.md"
        alias: "recruiter-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/reviver-agent.agent.md"
        alias: "reviver-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/feedback-loop-optimizer-agent.agent.md"
        alias: "feedback-loop-optimizer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/documenter-agent.agent.md"
        alias: "documenter-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/team-installer-agent.agent.md"
        alias: "team-installer-agent"
      - uri: "https://raw.githubusercontent.com/a5c-ai/registry/main/agents/development/product-optimizer-agent.agent.md"
        alias: "product-optimizer-agent"
a5c_auto_mode: true
