name: "Observability Aggregate"
description: "Download observability artifacts from previous jobs and aggregate into a single JSON file"
author: "a5c.ai"
runs:
  using: "composite"
  steps:
    - name: Download observability artifacts
      uses: actions/download-artifact@v4
      with:
        name: observability
        path: observability_artifacts

    - name: Aggregate
      shell: bash
      run: |
        set -euo pipefail
        out="observability.aggregate.json"
        if [ ! -d observability_artifacts ]; then
          echo "No observability artifacts directory found; writing empty aggregate." >&2
          echo '{}' > "$out"
          exit 0
        fi
        files=(observability_artifacts/**/*.json observability_artifacts/*.json)
        found=()
        for f in "${files[@]}"; do
          if [ -f "$f" ]; then found+=("$f"); fi
        done
        if [ ${#found[@]} -eq 0 ]; then
          echo "No JSON files found in artifacts; writing empty aggregate." >&2
          echo '{}' > "$out"
          exit 0
        fi
        # Aggregate into an object keyed by index
        idx=0
        printf '{"runs":[' > "$out"
        for f in "${found[@]}"; do
          if [ $idx -gt 0 ]; then printf ',' >> "$out"; fi
          # Validate JSON and append
          if jq -e . "$f" >/dev/null 2>&1; then
            jq -c . "$f" >> "$out"
            idx=$((idx+1))
          fi
        done
        printf ']}' >> "$out"

    - name: Upload aggregate
      uses: actions/upload-artifact@v4
      with:
        name: observability-aggregate
        path: observability.aggregate.json

branding:
  icon: layers
  color: green
