name: a5c-reactor-checks
on:
  # check_run:
  check_suite:
env:
  RUNNER_NAME: reactor

permissions:
  contents: write
  packages: read
  id-token: write
  actions: write
  statuses: write
  checks: write
  repository-projects: write
  pull-requests: write
jobs:
  reactor:
    uses: ./.github/workflows/a5c-base.yml
    secrets: inherit
    with:
      runner_name: reactor
      runs_on: ubuntu-latest
