name: a5c-reactor-issues
on:
  issue_comment:
    types:
      - created
      # - edited
      # - deleted
  issues:
    types:
      - labeled
      - opened
    #  - closed
    #  - milestoned
    #  - demilestoned
    #  - reopened
    #  - locked
    #  - unlocked
    #  - transferred
    #  - assigned
    #  - edited
    #  - pinned
    #  - unpinned
    #  - unlabeled
env:
  RUNNER_NAME: reactor

permissions:
  contents: write
  packages: read
  id-token: write
  actions: write
  statuses: write
  checks: write
  repository-projects: write
  pull-requests: write
  issues: write
jobs:
  reactor:
    uses: ./.github/workflows/a5c-base.yml
    secrets: inherit
    with:
      runner_name: reactor
      runs_on: ubuntu-latest
