name: a5c-reactor
on:
  # push:
  pull_request:
    types:
      - labeled
    #  - opened
    #  - reopened
    #  - ready_for_review
    #  - synchronize
    #  - assigned
    #  - unassigned
    #  - unlabeled
    #  - locked
    #  - unlocked
    #  - closed
    #  - edited
    #  - converted_to_draft
    #  - auto_merge_enabled
    #  - auto_merge_disabled
    #  - auto_merge_enabled
    #  - review_requested
    #  - review_request_removed
    #  - milestoned
    #  - demilestoned
    #  - enqueued
    #  - dequeued
  # issue_comment:
  #   types:
  #     - created
  #     - edited
  #     - deleted
  issues:
    types:
      - labeled
    #  - closed
    #  - opened
    #  - milestoned
    #  - demilestoned
    #  - reopened
    #  - locked
    #  - unlocked
    #  - transferred
    #  - assigned
    #  - edited
    #  - pinned
    #  - unpinned
    #  - unlabeled
  # workflow_run:
  #   types: [completed]
  #   workflows:
  #   - abc
  #   branches: [a5c/main,main]
  # workflow_dispatch:
  repository_dispatch:
  # check_run:
  # check_suite:
env:
  RUNNER_NAME: reactor

permissions:
  contents: write
  packages: read
  id-token: write
  actions: write
  statuses: write
  checks: write
  repository-projects: write
  pull-requests: write
jobs:
  reactor:
    uses: ./.github/workflows/a5c-base.yml
    secrets: inherit
    with:
      runner_name: reactor
      runs_on: ubuntu-latest
      events_path: .a5c/events/
