name: a5c

on:
  workflow_run:
    workflows: [Tests, Build, Typecheck]
    types: [completed]

jobs:
  dispatch:
    if: ${{ github.event.workflow_run.conclusion != '' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "a5c meta workflow hook"
