name: Docs Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs-lint.yml"
      - "scripts/docs-lint.sh"
  push:
    branches: [a5c/main]
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/docs-lint.yml"
      - "scripts/docs-lint.sh"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Make script executable
        run: chmod +x scripts/docs-lint.sh
      - name: Run docs lint
        run: ./scripts/docs-lint.sh

  codespell:
    name: Docs Spellcheck (codespell)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install codespell
        run: |
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check --no-color --no-python-version-warning codespell
      - name: Run codespell
        run: |
          codespell --version
          # Use repo config; quick scan of markdown and docs + top-level files
          codespell \
            --config .codespellrc \
            -q 3 \
            .

  markdownlint:
    name: Markdownlint (markdownlint-cli2)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Run markdownlint-cli2
        run: |
          npx --yes markdownlint-cli2 "**/*.md" "!node_modules" "!dist"
