name: PR Size Labels

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    name: Label PR by size
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ensure size labels exist
        uses: actions/github-script@v7
        with:
          script: |
            const labels = [
              { name: 'size:XS', color: 'ededed', description: 'PR size < 10 changed lines' },
              { name: 'size:S',  color: 'b2f5ea', description: 'PR size < 50 changed lines' },
              { name: 'size:M',  color: 'ffec99', description: 'PR size < 200 changed lines' },
              { name: 'size:L',  color: 'ffadad', description: 'PR size < 500 changed lines' },
              { name: 'size:XL', color: 'ff4d4f', description: 'PR size ≥ 500 changed lines' },
            ];
            for (const l of labels) {
              try {
                // Upsert label to ensure color/description stay consistent
                await github.rest.issues.updateLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: l.name,
                  new_name: l.name,
                  color: l.color.replace('#',''),
                  description: l.description,
                });
              } catch (e) {
                // Create if it doesn't exist
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: l.name,
                  color: l.color.replace('#',''),
                  description: l.description,
                });
              }
            }
      - name: Apply size label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size:XS"
          xs_max_size: "9"
          s_label: "size:S"
          s_max_size: "49"
          m_label: "size:M"
          m_max_size: "199"
          l_label: "size:L"
          l_max_size: "499"
          xl_label: "size:XL"
          fail_if_xl: "false"
          files_to_ignore: ""
