name: Reactor
on:
  push:
  pull_request:
  issue_comment:
  issues:
  workflow_dispatch:
  repository_dispatch:
  check_run:
  check_suite:

jobs:
  reactor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enrich and run reactor with actual github context
        env:
          NODE_AUTH_TOKEN: ${{ secrets.A5C_AGENT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ env.NPM_CONFIG_USERCONFIG }}
          GITHUB_TOKEN: ${{ secrets.A5C_AGENT_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          npx -y "$A5C_PKG_SPEC" enrich \
            --in "$GITHUB_EVENT_PATH" \
            --out out.enrich.json \
            --use-github
          # enriched structure exists
          jq -e '.enriched and .payload and (.labels // []) != null' out.enrich.json >/dev/null
          cat out.enrich.json
          npx -y "$A5C_PKG_SPEC" reactor \
            --in out.enrich.json \
            --out out.reactor.json \
            --file example/.a5c/events/reactor.yaml
          # list of events to emit
          jq -r '.events[]' out.reactor.json
          cat out.reactor.json
          # emit the events using the CLI (repository_dispatch)
          npx -y "$A5C_PKG_SPEC" emit \
            --in out.reactor.json \
            --sink github
          echo "Done emitting events via emit command"
