name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"
      - name: Install
        env:
          HUSKY: 0
        run: |
          if [ -f package-lock.json ]; then
            echo "Attempting clean install via npm ci..."
            if ! npm ci; then
              echo "npm ci failed (likely lockfile mismatch). Falling back to npm install to update lockfile..."
              npm install
            fi
          else
            npm install
          fi
      - name: Build
        run: npm run -s build
      - name: Setup Node.js for npmjs (main only)
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
      - name: Publish to npmjs (main only)
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -euo pipefail
          # Ensure dist exists (semantic-release should have built during build step)
          test -d dist || { echo "dist missing"; exit 1; }
          # Read version from package.json
          VERSION=$(node -p "require('./package.json').version")
          NAME=$(node -p "require('./package.json').name")
          echo "Attempt publish ${NAME}@${VERSION} to registry.npmjs.org"
          # Fast pre-check (can be stale due to npm propagation); best-effort only
          if npm view "${NAME}@${VERSION}" version --registry=https://registry.npmjs.org > /dev/null 2>&1; then
            echo "Version already exists on npmjs, skipping publish."
            exit 0
          fi

          # Temporarily override project .npmrc to ensure scoped package publishes to npmjs (not GitHub Packages)
          BACKUP_NPMRC=false
          if [ -f .npmrc ]; then
            mv .npmrc .npmrc.gpr
            BACKUP_NPMRC=true
          fi
          # Always restore .npmrc on exit
          cleanup() {
            if [ "$BACKUP_NPMRC" = true ]; then
              rm -f .npmrc || true
              mv .npmrc.gpr .npmrc || true
            else
              rm -f .npmrc || true
            fi
          }
          trap cleanup EXIT

          cat > .npmrc <<'NPMRC'
          fund=false
          audit=false
          save-exact=true
          //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}
          @a5c-ai:registry=https://registry.npmjs.org/
          NPMRC

          echo "Auth check against npmjs: $(npm whoami --registry=https://registry.npmjs.org || echo 'not authenticated')"

          # Retry helper for transient errors; treat already-published conflicts as success
          attempts=0
          max_attempts=3
          backoff=5
          while true; do
            attempts=$((attempts+1))
            echo "npm publish attempt ${attempts}/${max_attempts}"
            if out=$(npm publish --registry=https://registry.npmjs.org --access public 2>&1); then
              echo "$out"
              break
            fi
            rc=$?
            echo "$out"
            # If version is already published, consider success and exit 0
            if echo "$out" | grep -Eiq 'You cannot publish over the previously published versions|EPUBLISHCONFLICT|previously published'; then
              echo "Version already exists on npmjs (detected after publish). Skipping as success."
              exit 0
            fi
            # Retry on transient errors
            if [ $attempts -lt $max_attempts ] && echo "$out" | grep -Eiq '(5[0-9]{2}|Bad Gateway|Service Unavailable|ETIMEDOUT|ECONNRESET|EAI_AGAIN|ESOCKETTIMEDOUT|network error|socket hang up|fetch failed|rate limit)'; then
              echo "Transient error detected. Sleeping ${backoff}s before retry..."
              sleep "$backoff"
              backoff=$((backoff*2))
              continue
            fi
            exit "$rc"
          done
