name: Typecheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [a5c/main, main]

jobs:
  typecheck:
    name: TypeScript Typecheck
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Typecheck
        id: tsc
        run: |
          set -euo pipefail
          if npm run -s typecheck; then
            echo "result=success" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "result=failure" >> "$GITHUB_OUTPUT"
            exit 1
          fi

      - name: Step summary
        if: always()
        run: |
          echo "## Typecheck on Node ${{ matrix.node }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Result: ${{ steps.tsc.outputs.result || 'unknown' }}" >> "$GITHUB_STEP_SUMMARY"

